### ISSUE TITLE
Provide alternative implementation as a project plugin

### ISSUE THREAD

**Issue by friscoMad** [austinarbor/version-catalog-generator#117]
First of all, thank you for your nice work.
Maybe I am alone here but my use case would be to republish multiple BOMs as a single catalog, like creating my own Spring BoM as a catalog to be able to provide it for multiple projects inside my organization.
I thought that I could use your plugin but I don't think I can as it is heavily oriented towards a settings plugin (I tried to add it as a dependency and directly use functions but it doesn't work.

My idea would be to do something like this:

```kts
plugins {
    `version-catalog`
    id("dev.aga.gradle.version-catalog-generator-XX") version "1.5.0"
}

catalog {
    // declare the aliases, bundles and versions in this block
    versionCatalog {
        from(toml("springBootDependencies")) // Add some way to define a prefix 
        from(toml("mockitoDependencies")) 
    }
}
```
So this catalog can be published and then imported into other projects.
It is possible to create a settings convention plugin to import your plugin with the proper configuration but it will be doing extra work per project when it can be generated a single time.

I assume that a big chunk of the logic can be shared between the current settings plugin and a project plugin but anyways it would be a big effort to add a second plugin and support it so I understand if it is not possible.

**Comment by austinarbor** [comment]
hi @friscoMad thanks for your kind words - while your suggestion would definitely be a useful feature, it is a bit different from what the plugin does now. The plugin currently is focused on _consuming_ BOMs, whereas the plugin you are looking for would be producing them as a version catalog instead.

At this point in time I don't plan on implementing this feature but I will reply back here if I ever do!
